services:
  groundhog:
    build: .
    container_name: groundhog
    ports:
      - "8504:8000"
    networks:
      - caddy-net
    restart: unless-stopped
    volumes:
      - groundhog-srtm:/app/mvp_backend/srtm_cache
      - groundhog-cache:/app/mvp_backend/route_cache_data

networks:
  caddy-net:
    external: true

volumes:
  groundhog-srtm:
  groundhog-cache:
